name: "github-ejs-build"
on:
  workflow_dispatch:
    inputs:
      docker_image_name:
        required: true
        type: string
        default: "ejs"
        description: "Docker Image name"
permissions:
  actions: read
  id-token: write
  packages: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.event.inputs.docker_image_name }}
    steps:
      - name: Print Inputs
        run: echo "${{ toJSON(github.event.inputs) }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Setup JFrog Fly
        uses: jfrog/fly-action@v1
      - name: NPM Install
        run: npm install --omit=dev
      - name: Python Env
        run: pip install --upgrade pip setuptools wheel
      - name: Python Build
        run: |
          pip install -r requirements.txt
          python setup.py sdist bdist_wheel
      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        id: build
        with:
          push: true
          tags: ${{ env.FLY_REGISTRY_SUBDOMAIN }}/docker/${{ env.IMAGE_NAME }}:${{ github.run_number }}
          provenance: false
